version: "3.7"

services:
  db:
    image: postgres:11.4
    env_file: config.env
    volumes:
      - db-tgbot-data:/var/lib/postgresql/data
  tgbot:
    image: infocomtc/test/tgbot
    restart: on-failure
    depends_on:
      - db
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5003:5003"
    env_file: config.env
    volumes:
      - ../:/tgbot
    command: pipenv run python -m tg_bot

volumes:
  db-tgbot-data:
